# Generated by Django 4.2.5 on 2024-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_p', '0006_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='category_name', max_length=255, unique=True),
        ),
    ]
